// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0SY8zOJ52wNEmD4ZwmgNq8RFmSdvT9Ns',
    appId: '1:539678503825:web:897b0883e6600b43772030',
    messagingSenderId: '539678503825',
    projectId: 'social-media-app-e18c1',
    authDomain: 'social-media-app-e18c1.firebaseapp.com',
    storageBucket: 'social-media-app-e18c1.appspot.com',
    measurementId: 'G-EV3NYTLP5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV_TAiFuGhSXNpW5rQSkJJynwTcjkhU2o',
    appId: '1:539678503825:android:1c20157726ca8af8772030',
    messagingSenderId: '539678503825',
    projectId: 'social-media-app-e18c1',
    storageBucket: 'social-media-app-e18c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0CtMvUZSsh-3NBsfLsLfDs_6S3j56tso',
    appId: '1:539678503825:ios:fc2478028baa696e772030',
    messagingSenderId: '539678503825',
    projectId: 'social-media-app-e18c1',
    storageBucket: 'social-media-app-e18c1.appspot.com',
    iosBundleId: 'com.example.socialmediaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0CtMvUZSsh-3NBsfLsLfDs_6S3j56tso',
    appId: '1:539678503825:ios:e69dff3a4c57f3a9772030',
    messagingSenderId: '539678503825',
    projectId: 'social-media-app-e18c1',
    storageBucket: 'social-media-app-e18c1.appspot.com',
    iosBundleId: 'com.example.socialmediaapp.RunnerTests',
  );
}
